#!/bin/sh
# The migrate job (GCP-04): apply migrations, then set the RLS role passwords.
#
# The migrations create app_staff / app_client / app_employee with DEVELOPMENT
# passwords (rls_roles_and_policies, employee_isolation). On any real database
# those must not survive, so after `migrate deploy` this sets each role's
# password from the environment — injected by Cloud Run from Secret Manager,
# values generated by the owner (hex, so they need no SQL quoting). A variable
# that is not set leaves that role untouched (local / CI keep the dev ones).
set -eu

npx prisma migrate deploy

sql=""
for pair in "app_staff:${APP_STAFF_DB_PASSWORD:-}" "app_client:${APP_CLIENT_DB_PASSWORD:-}" "app_employee:${APP_EMPLOYEE_DB_PASSWORD:-}"; do
  role="${pair%%:*}"
  pw="${pair#*:}"
  [ -z "$pw" ] && continue
  case "$pw" in
    *[!0-9a-fA-F]*) echo "refusing: the ${role} password must be hex" >&2; exit 1 ;;
  esac
  sql="${sql}ALTER ROLE ${role} PASSWORD '${pw}';
"
done

if [ -n "$sql" ]; then
  printf '%s' "$sql" | npx prisma db execute --stdin
  echo "role passwords set: $(printf '%s' "$sql" | grep -c 'ALTER ROLE')"
fi
