-- SS-06a (ADR-011): invitations, first passwords, password reset.
-- Generated by `prisma migrate diff`, then the backfill and grants below.

-- CreateEnum
CREATE TYPE "AccountTokenPurpose" AS ENUM ('invite', 'reset');

-- AlterEnum
ALTER TYPE "UserStatus" ADD VALUE 'invited';

-- AlterTable
ALTER TABLE "auth_users" ADD COLUMN     "password_set_at" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "auth_account_tokens" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "purpose" "AccountTokenPurpose" NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "used_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_account_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "auth_account_tokens_token_hash_key" ON "auth_account_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "auth_account_tokens_user_id_purpose_idx" ON "auth_account_tokens"("user_id", "purpose");

-- AddForeignKey
ALTER TABLE "auth_account_tokens" ADD CONSTRAINT "auth_account_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- Every account that exists today was created WITH a password (staff, client
-- reps, the seed employee), so each counts as having set one.
UPDATE "auth_users" SET "password_set_at" = "created_at" WHERE "password_set_at" IS NULL;

-- A system table like auth_users: staff connection only, no RLS — isolation is
-- application-enforced (tokens are looked up by hash, never listed). The
-- employee and client connections get nothing.
GRANT SELECT, INSERT, UPDATE, DELETE ON "auth_account_tokens" TO app_staff;
